spring:
  application:
    name: authservice
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: http://localhost:8083
          predicates:
            - Path=/admin-service/**
          filter:
            - StripPrefix=1
server:
  port: 9092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
      hostname: localhost

#Zuul:
#  routes:
#    admin-service:
#      path: /admin-service/**
#      serviceId: ADMIN-SERVICE
#      url: http://localhost:8083